-- ============================================================================
-- MYPLOT.NG — SUPABASE SCHEMA
-- ----------------------------------------------------------------------------
-- Covers the four live forms on myplot.ng (CheckMyPlot requests, SellMyPlot
-- listings, BuyMyPlot inquiries, and community fraud reports), plus the
-- referral system: anyone can sign up for a referral code (via a real
-- Supabase Auth email/password account), BUYERS enter that code when
-- submitting a BuyMyPlot inquiry, and once the listing they were inquiring
-- about actually sells, 1% of the total sale price is set aside for
-- whoever referred that buyer, paid out of MyPlot's own 5% commission so
-- buyers and sellers never pay anything extra. Referrers log into their
-- own dashboard to see only their own referral activity, never anyone
-- else's, and never a seller's or another referrer's private details.
--
-- IMPORTANT: the referral credit follows the BUYER, not the seller. A seller
-- who lists a plot earns nothing for anyone by listing it, the referral is
-- only triggered by whoever brought the buyer whose purchase closed the sale.
--
-- IMPORTANT: referral codes are generated by the database itself (see the
-- trigger in section 2B below), never chosen by the referrer and never sent
-- by the client. The signup form should not include a referral_code field.
--
-- Field names below match the actual <input name="..."> attributes already
-- live in the site's HTML, so the engineer wiring up the forms can map
-- straight from form field to column with no renaming.
--
-- HOW TO USE:
-- 1. In the Supabase dashboard, under Authentication, enable Email/Password
--    sign-in if it is not already on. This is required before referrer
--    signup can work at all.
-- 2. Open your Supabase project → SQL Editor → New query.
-- 3. Paste this whole file and run it once. It creates all tables in the
--    correct dependency order, sets up the referral code trigger, turns
--    on Row Level Security, and sets both the public submission policies
--    and the authenticated referrer dashboard policies.
-- 4. The site's forms, referrer signup, login, and dashboard pages are
--    already built and already call Supabase directly (raw REST calls to
--    /rest/v1/... and /auth/v1/..., using the public "anon" key, no SDK
--    needed). Your engineer's remaining job is to confirm the "Confirm
--    email" setting under Authentication matches what you want (default:
--    on, meaning a referrer must click a confirmation email link before
--    their first login creates their profile), then test the whole flow
--    end to end against your real Supabase project before this goes live.
-- 5. When a sale completes: an admin (via the Supabase dashboard, not the
--    public site) updates the relevant sell_submissions row: sets status to
--    'sold', fills in sale_price and buyer_inquiry_id (which buy_inquiries
--    row was the buyer who actually purchased), and myplot_commission /
--    referral_commission are then calculated from those two fields.
-- 6. You (Dr. Femi) view submissions either in the Supabase Table Editor
--    directly, or by setting up email/Slack alerts on new rows (see note
--    at the bottom of this file).
-- ============================================================================


-- ---------- 1. CHECKMYPLOT REQUESTS ----------
-- Source: check/index.html, "Request a CheckMyPlot report" form

create table check_requests (
  id              uuid primary key default gen_random_uuid(),
  created_at      timestamptz not null default now(),
  status          text not null default 'new',   -- new / in_review / completed / cancelled

  name            text not null,
  phone           text not null,
  email           text not null,
  plot_location   text not null,                 -- e.g. "Gwarinpa, Abuja"
  plot_count      text,                          -- free text, e.g. "1" or "8 for a multi plot estate"
  plot_reference  text,                          -- survey plan / plot number, if known
  addon_insight   boolean not null default false,
  addon_foresight boolean not null default false,
  details         text,                          -- seller name, documents already held, etc.

  constraint check_requests_status_valid
    check (status in ('new', 'in_review', 'completed', 'cancelled'))
);

comment on table check_requests is 'CheckMyPlot report requests submitted from check/index.html';


-- ---------- 2. REFERRERS ----------
-- Source: refer/index.html, "Become a referrer" signup form
-- Created before buy_inquiries, which references referral_code below.

create table referrers (
  id                  uuid primary key default gen_random_uuid(),
  created_at          timestamptz not null default now(),
  status              text not null default 'pending',   -- pending / active / suspended

  user_id             uuid not null unique references auth.users(id),  -- the referrer's login account
  name                text not null,
  phone               text not null,
  email               text not null,
  referral_code       text not null unique,   -- auto-generated on insert, see trigger below,
                                              -- the client never supplies this value

  bank_account_name   text,                   -- name on the bank account
  bank_account_number text,                   -- account number
  bank_name           text,                   -- e.g. "GTBank", "Access Bank"

  total_earned        numeric(14,2) not null default 0,  -- running total of paid-out referral commission

  constraint referrers_status_valid
    check (status in ('pending', 'active', 'suspended'))
);

comment on table referrers is 'People who signed up (via Supabase Auth) to refer buyers to MyPlot and earn a share of commission when that buyer''s purchase closes. One row per authenticated referrer, linked via user_id.';


-- ---------- 2B. AUTO-GENERATED REFERRAL CODES ----------
-- Codes are generated by the database itself, never by the client, so two
-- people signing up at the same instant can never be handed the same code.
-- Format: 6 characters, uppercase letters and digits, excluding 0/O/1/I/L
-- since those are easy to misread when a referrer shares their code aloud
-- or over WhatsApp.

create or replace function generate_referral_code() returns text as $$
declare
  chars text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  candidate text;
  already_used boolean;
begin
  loop
    candidate := '';
    for i in 1..6 loop
      candidate := candidate || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    end loop;
    select exists(select 1 from referrers where referral_code = candidate) into already_used;
    exit when not already_used;
  end loop;
  return candidate;
end;
$$ language plpgsql;

create or replace function set_referral_code() returns trigger as $$
begin
  new.referral_code := generate_referral_code();
  return new;
end;
$$ language plpgsql;

create trigger trg_set_referral_code
before insert on referrers
for each row execute function set_referral_code();

-- Note for the engineer: because this trigger always overwrites
-- referral_code on insert, the signup form must not include a
-- referral_code field at all, whatever the client sends in that column is
-- discarded anyway.


-- ---------- 3. BUYMYPLOT INQUIRIES ----------
-- Source: buy/index.html, buyer inquiry form
-- Created before sell_submissions, which references buy_inquiries(id) below
-- to record which buyer's inquiry actually led to a completed sale.

create table buy_inquiries (
  id                 uuid primary key default gen_random_uuid(),
  created_at         timestamptz not null default now(),
  status             text not null default 'new',   -- new / contacted / closed

  name               text not null,
  phone              text not null,
  email              text not null,
  preferred_location text,                          -- e.g. "Guzape, Life Camp, Jahi"
  budget_range       text,                          -- free text, e.g. "N20,000,000 to N40,000,000"
  details            text,                          -- plot size, purpose, timeline, etc.

  -- ---- Referral tracking ----
  referral_code      text references referrers(referral_code),  -- code the BUYER entered, if any

  constraint buy_status_valid
    check (status in ('new', 'contacted', 'closed'))
);

comment on table buy_inquiries is 'BuyMyPlot inquiries, routed internally to the buyer relations team, never shown directly to sellers';


-- ---------- 4. SELLMYPLOT SUBMISSIONS ----------
-- Source: sell/index.html, "Submit a listing" form

create table sell_submissions (
  id                    uuid primary key default gen_random_uuid(),
  created_at            timestamptz not null default now(),
  status                text not null default 'new',   -- new / awaiting_check / listed / sold / rejected

  name                  text not null,
  phone                 text not null,
  email                 text not null,
  property_type         text not null,                 -- 'land' | 'building'
  listing_type          text not null,                 -- 'plot' | 'estate'
  estate_plot_count     text,                          -- only relevant when listing_type = 'estate'
  listing_location      text not null,                 -- e.g. "Guzape, Abuja"
  listing_reference     text,
  seller_type           text not null,                 -- 'individual' | 'agent' | 'developer'
  details               text,                          -- documents held, asking price, timeline, etc.

  -- ---- Sale & referral tracking ----
  -- Filled in by an admin once a sale actually completes, not by the seller
  -- at listing time. The referral credit flows through buyer_inquiry_id,
  -- not from this table directly — find which buyer actually purchased,
  -- link their inquiry here, and their referral_code (if any) determines
  -- who gets paid.
  buyer_inquiry_id      uuid references buy_inquiries(id),  -- which buyer's inquiry led to this sale
  sale_price            numeric(14,2),   -- filled in once status = 'sold'
  myplot_commission     numeric(14,2),   -- 10% of sale_price, paid by the seller, filled in on sale
  buyer_legal_admin_fee numeric(14,2),   -- 5% of sale_price, paid by the buyer separately, filled in on sale
  referral_commission   numeric(14,2),   -- 1% of sale_price directly, not derived from myplot_commission,
                                         -- only if the linked buyer_inquiry had a referral_code
  referral_paid         boolean not null default false,  -- has the referrer actually been paid out

  constraint sell_status_valid
    check (status in ('new', 'awaiting_check', 'listed', 'sold', 'rejected')),
  constraint sell_property_type_valid
    check (property_type in ('land', 'building')),
  constraint sell_listing_type_valid
    check (listing_type in ('plot', 'estate')),
  constraint sell_seller_type_valid
    check (seller_type in ('individual', 'agent', 'developer'))
);

comment on table sell_submissions is 'SellMyPlot listing submissions from sell/index.html, pending CheckMyPlot before going live. Referral credit for a sale is attributed via buyer_inquiry_id, not by anything the seller entered.';


-- ---------- 5. COMMUNITY FRAUD REPORTS ----------
-- Source: report/index.html, "Report land" form
-- NOTE: this table is sensitive. The site tells reporters their identity is
-- never made public — see the RLS + access note at the bottom of this file.

create table fraud_reports (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz not null default now(),
  status        text not null default 'new',   -- new / investigating / resolved / dismissed

  name          text not null,
  phone         text not null,
  plot_location text not null,                 -- district, area, or nearest landmark
  agent_name    text,                          -- agent being reported, if applicable
  report_type   text not null,                 -- see check constraint below
  details       text not null,

  constraint fraud_status_valid
    check (status in ('new', 'investigating', 'resolved', 'dismissed')),
  constraint fraud_report_type_valid
    check (report_type in (
      'duplicate_sale', 'forged_title', 'disputed_claim',
      'suspicious_agent', 'other'
    ))
);

comment on table fraud_reports is 'Community fraud reports. Reporter identity must never be exposed publicly or to the person/agent being reported.';


-- ---------- 6. ADMINS ----------
-- Staff with full view/edit access to every submission across every table,
-- for the admin page (see admin/index.html). This is NOT self-service.
-- There is deliberately no public or authenticated INSERT policy on this
-- table below, a row here only ever gets created by you, directly in the
-- Supabase Table Editor, using the service role which bypasses RLS.
--
-- HOW TO ADD A NEW ADMIN:
-- 1. Have that person create an account the normal way, at refer/index.html
--    (a referrer account and an admin account are the same underlying
--    Supabase Auth login, admins table membership is what adds admin
--    powers on top, it does not replace their referrer access).
-- 2. In the Supabase dashboard, go to Authentication → Users, find their
--    email, and copy their User UID.
-- 3. Go to Table Editor → admins → Insert row, paste that UID into
--    user_id, and fill in their name and email.
-- 4. They can now log in at admin/index.html with the same email and
--    password they used to sign up.

create table admins (
  id         uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_id    uuid not null unique references auth.users(id),
  name       text not null,
  email      text not null
);

comment on table admins is 'Staff with full view/edit access to every table. Rows are added manually via the Supabase dashboard only, never through public signup.';


-- ---------- 7. ESCROW TRACKING ----------
-- MyPlot is NOT a deposit-taking bank (see Terms of Use, Clause 7) and this
-- table does NOT move money. It is a manual staff tracking layer sitting on
-- top of a real bank account: the buyer wires the purchase sum to MyPlot's
-- bank account, staff manually confirm the transfer arrived (by checking the
-- bank statement/app), mark it here, hold it until the transaction closes,
-- then release it, deducting MyPlot's fees at source per the Terms of Use.
-- No payment gateway or automated bank integration exists yet, this is the
-- record-keeping/status layer requested so that stage can be added later
-- without changing how staff work day to day.
--
-- MyPlot's receiving account (shown to the buyer once a sale is agreed,
-- together with the reference_code below so staff can match the transfer):
--   Account name:   MyPlot.NG
--   Account number: 9652683212
--   Bank:           Providus Bank

create table escrow_transactions (
  id                    uuid primary key default gen_random_uuid(),
  created_at            timestamptz not null default now(),
  reference_code        text not null unique,   -- auto-generated, quote this on the bank transfer

  sell_submission_id    uuid references sell_submissions(id),  -- the listing being sold
  buyer_inquiry_id      uuid references buy_inquiries(id),     -- the buyer paying in
  buyer_name            text not null,
  buyer_phone           text not null,

  amount_expected       numeric(14,2) not null,  -- full purchase sum the buyer is expected to pay in
  amount_received       numeric(14,2),           -- filled in by staff once confirmed on the bank statement
  date_received         date,

  status                text not null default 'awaiting_funds',
    -- awaiting_funds : reference issued to buyer, nothing received yet
    -- funds_received : staff confirmed the transfer landed, not yet reconciled/held
    -- held           : reconciled and held pending transaction completion
    -- released       : paid out to the seller (fees deducted at source), transaction complete
    -- refunded       : returned to the buyer, sale did not complete
    -- disputed       : a problem exists, do not release until resolved

  release_amount_seller numeric(14,2),   -- what the seller actually receives, after MyPlot's fees
  release_date          date,
  released_by           text,            -- staff member who authorised the release
  notes                 text,            -- free text: bank reference seen, follow-ups, disputes, etc.

  constraint escrow_status_valid
    check (status in ('awaiting_funds', 'funds_received', 'held', 'released', 'refunded', 'disputed'))
);

comment on table escrow_transactions is 'Manual staff tracking of buyer funds held pending a sale closing. Records status only, it does not move money itself, staff confirm transfers by hand against MyPlot''s real bank account until automated banking integration is added.';

-- Reference codes are generated by the database, same pattern as referral
-- codes, so two transactions started at once can never collide, and staff
-- never have to invent one by hand. Format: ESC- plus 6 characters.

create or replace function generate_escrow_reference() returns text as $$
declare
  chars text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  candidate text;
  already_used boolean;
begin
  loop
    candidate := 'ESC-';
    for i in 1..6 loop
      candidate := candidate || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    end loop;
    select exists(select 1 from escrow_transactions where reference_code = candidate) into already_used;
    exit when not already_used;
  end loop;
  return candidate;
end;
$$ language plpgsql;

create or replace function set_escrow_reference() returns trigger as $$
begin
  if new.reference_code is null or new.reference_code = '' then
    new.reference_code := generate_escrow_reference();
  end if;
  return new;
end;
$$ language plpgsql;

create trigger trg_set_escrow_reference
before insert on escrow_transactions
for each row execute function set_escrow_reference();


-- ============================================================================
-- ROW LEVEL SECURITY
-- ----------------------------------------------------------------------------
-- Without this section, anyone with your public "anon" key (which is visible
-- in the site's own JavaScript) could read every submission, including
-- names, phone numbers, and fraud reports. Two access levels now exist:
--   - anon (not logged in): can INSERT into the four public forms, cannot
--     read anything back.
--   - authenticated (logged in as a referrer): can additionally read their
--     OWN referrer profile, the buy_inquiries rows that carried their code,
--     and the sell_submissions rows those inquiries led to, nothing else.
-- Nobody, at either level, can read another referrer's payout details, a
-- seller's contact info, or a fraud report. Only you, via the Supabase
-- dashboard, can see everything.
-- ============================================================================

alter table check_requests      enable row level security;
alter table referrers           enable row level security;
alter table buy_inquiries       enable row level security;
alter table sell_submissions    enable row level security;
alter table fraud_reports       enable row level security;
alter table admins              enable row level security;
alter table escrow_transactions enable row level security;


-- ---- Referrer signup & dashboard access (authenticated only) ----
-- Referrers must create a Supabase Auth account first (email + password),
-- then this table stores their profile, linked one-to-one via user_id.
-- There is no anon insert policy here any more, signing up as a referrer
-- now requires being logged in, which happens the instant auth.signUp()
-- succeeds on the client.

create policy "A referrer can create their own profile"
  on referrers for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "A referrer can view their own profile"
  on referrers for select
  to authenticated
  using (user_id = auth.uid());

create policy "A referrer can view inquiries that carried their code"
  on buy_inquiries for select
  to authenticated
  using (
    referral_code = (select referral_code from referrers where user_id = auth.uid())
  );

create policy "A referrer can view sales linked to their referrals"
  on sell_submissions for select
  to authenticated
  using (
    buyer_inquiry_id in (
      select id from buy_inquiries
      where referral_code = (select referral_code from referrers where user_id = auth.uid())
    )
  );

-- Note: a referrer's SELECT on sell_submissions returns whatever columns
-- the query asks for, including sale_price and referral_commission on rows
-- that belong to them, that is the point of the dashboard. It does NOT let
-- them see other sellers' rows, or any row not linked to their own code.


-- ---- Public form submissions (anonymous, insert-only) ----

create policy "Public can submit check requests"
  on check_requests for insert
  to anon
  with check (true);

create policy "Public can submit buy inquiries"
  on buy_inquiries for insert
  to anon
  with check (true);

create policy "Public can submit sell listings"
  on sell_submissions for insert
  to anon
  with check (true);

create policy "Public can submit fraud reports"
  on fraud_reports for insert
  to anon
  with check (true);

-- No SELECT / UPDATE / DELETE policies exist for the anon role at all. This
-- means the public website, before anyone logs in, can never read back
-- submissions, only Supabase's dashboard (logged in as project owner), an
-- authenticated referrer viewing their own linked rows as above, or a
-- properly authenticated admin as below, can.


-- ---- Admin access (authenticated + present in the admins table) ----
-- Full read and update across every table, for admin/index.html. Every
-- policy below checks the same thing: is this logged-in user's id present
-- in the admins table. If they are not in that table, none of these
-- policies apply to them, they fall back to the ordinary anon-level access
-- (none) or referrer-level access (their own rows only) above. Admin status
-- is never self-granted, see the admins table definition for how someone
-- actually becomes an admin.

create policy "A user can check their own admin status"
  on admins for select
  to authenticated
  using (user_id = auth.uid());

create policy "Admins can view all check requests"
  on check_requests for select to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can update check requests"
  on check_requests for update to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can view all sell submissions"
  on sell_submissions for select to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can update sell submissions"
  on sell_submissions for update to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can view all buy inquiries"
  on buy_inquiries for select to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can update buy inquiries"
  on buy_inquiries for update to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can view all fraud reports"
  on fraud_reports for select to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can update fraud reports"
  on fraud_reports for update to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can view all referrers"
  on referrers for select to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can update referrers"
  on referrers for update to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can view all escrow transactions"
  on escrow_transactions for select to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can create escrow transactions"
  on escrow_transactions for insert to authenticated
  with check (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can update escrow transactions"
  on escrow_transactions for update to authenticated
  using (exists (select 1 from admins where user_id = auth.uid()));

-- No anon policy exists on escrow_transactions at all: a transaction is only
-- ever created by a staff member on the admin page once a sale is agreed,
-- never submitted by the public.

-- Note: a referrer who is ALSO an admin (e.g. you, using your own referral
-- code) still only gets ONE set of rows back per query, Postgres does not
-- duplicate rows just because two policies both happen to allow the same
-- row. Their admin access simply widens what else becomes visible.


-- ============================================================================
-- HOW YOU'LL ACTUALLY SEE SUBMISSIONS
-- ----------------------------------------------------------------------------
-- Option A — Supabase Table Editor (no setup needed):
--   Project dashboard → Table Editor → pick a table. Every submission is a
--   row, sortable and filterable, immediately after someone submits a form.
--
-- Option B — Email alert on every new submission (recommended):
--   Project dashboard → Database → Webhooks → New webhook. Trigger it on
--   INSERT for each of the four tables, pointing at a small notification
--   service (e.g. Zapier, Make, or a simple email-sending Edge Function).
--   Ask your engineer to set this up once the tables exist, it's a short job.
--
-- Option C — Simple internal dashboard (later, not needed to launch):
--   A small authenticated admin page listing new submissions per table,
--   with the ability to change "status", and to record a completed sale
--   (linking buyer_inquiry_id and filling in sale_price on sell_submissions).
--   Worth building once volume grows past what email alerts can comfortably
--   handle, since recording a sale by hand in the Table Editor works fine
--   at low volume but gets tedious as listings grow.
-- ============================================================================
